### ISSUE TITLE
Error occur when writing to broken stream

### ISSUE THREAD

**Issue by yunnysunny** [yunnysunny/slogger#2]
When use pm2, the process.stdout is overwritten, it write to file stream in the   overwritten function. But if error occurs in the phase of  the writing file, it will raise such error:
```
[ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:427:19)
    at writeOrBuffer (_stream_writable.js:415:5)
    at WriteStream.Writable.write (_stream_writable.js:305:11)
    at SyncWriteStream.write (/pm2/lib/ProcessContainer.js:243:48)
    at Timeout.flushTimeout [as _onTimeout] (/mycode/node_modules/node-slogger/lib/LogPrinter.js:125:27)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ERR_STREAM_DESTROYED'
```

**Comment by yunnysunny** [comment]
fixed by pull request https://github.com/yunnysunny/slogger/pull/3
